---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2016
    transport:
      name: winrm
      elevated: true
    options:
      cpu: 2
      memory: 2048

suites:
  - name: default
    run_list:
      - recipe[windowsdev::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
